# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
  desc "Push a new builds to TestFlight"
  lane :beta do
    match(type:'appstore')
    build_app(scheme: "rndemo")
    upload_to_testflight
  end
  lane :prod do
    deliver(
      build_number: latest_testflight_build_number.to_s,
      submit_for_review: false,
      automatic_release: false,
      force: true,
      skip_metadata: false,
      skip_screenshots: true,
      skip_binary_upload: true
    )
  end
end 
